routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resources([
    'projects' => 'ProjectController', 
    'tasks' => 'TaskController'
]);

app/Project.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Project extends Model
{
    //
    protected $fillable = [ 
        'nama', 'tanggal_mulai', 'tanggal_target'
    ];
}

app/Task.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ProjectController.php
<?php

namespace App\Http\Controllers;
use App\Project;
use Illuminate\Http\Request;

class ProjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $projects = Project::all();
        return view('Projects.index',compact('projects'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('Projects.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validasi
        $validasi = $request->validate([
            'nama' => 'required|max:30',
            'tanggal_mulai' => 'required',
            'tanggal_target' => 'required',
        ]);

        Project::create ([
            'nama' => $request['nama'],
            'tanggal_mulai' => $request['tanggal_mulai'],
            'tanggal_target' => $request['tanggal_target'],
            'create_at' => now()
        ]);
        return redirect()->route('projects.index')->with(['message' => 'Projek berhasil ditambahkan']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $project = Project::find($id);
        return view ('Projects.edit',compact('project'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $validasi = $request->validate([
            'nama' => 'required|max:30', 
            'tanggal_mulai' => 'required',
            'tanggal_target' => 'required',
        ]);
        $project = Project::find($id);
        $project->nama = $request['nama'];
        $project->tanggal_mulai = $request['tanggal_mulai'];
        $project->tanggal_target = $request['tanggal_target'];
        $project->updated_at = now();
        $project-> save();

        return redirect()->route('projects.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $project = Project::find($id);
        $project->delete();

        return redirect()->back()->with(['message' => 'Projek berhasil dihapus!']);
    }
}

app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;

class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/Projects/create.blade.php
@extends('layouts.app')

@section('title')
    Tambah Project
@endsection

@section('content')

<form action="{{ route('projects.store') }}" method="POST">
  <div class="form-group">
    @csrf
        <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" class="form-control" name="nama" aria-describedby="emailHelp">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <div class="form-group">
                    <label for="tanggal_mulai">Tanggal Mulai</label>
                    <input type="date" class="form-control" name="tanggal_mulai">
                </div>
            </div>
            <div class="form-group col-md-6">
                <div class="form-group">
                    <label for="tanggal_target">Tanggal Target</label>
                    <input type="date" class="form-control" name="tanggal_target">
                </div>
            </div>
        </div>
    </div>

  <button type="submit" class="btn btn-primary">Tambah</button>
</form>
@endsection

resources/views/Projects/edit.blade.php
@extends('layouts.app')

@section('title')
    Tambah Project
@endsection

@section('content')

<form action="{{ route('projects.update', $project['id']) }}" method="POST">
  <div class="form-group">
    @csrf
    @method('put')
        <div class="form-group">
            <label for="nama">Nama</label>
            <input type="text" class="form-control" name="nama" aria-describedby="emailHelp" value="{{ $project['nama'] }}">
        </div>
        <div class="form-row">
            <div class="form-group col-md-6">
                <div class="form-group">
                    <label for="tanggal_mulai">Tanggal Mulai</label>
                    <input type="date" class="form-control" name="tanggal_mulai" value="{{ $project['tanggal_mulai'] }}">
                </div>
            </div>
            <div class="form-group col-md-6">
                <div class="form-group">
                    <label for="tanggal_target">Tanggal Target</label>
                    <input type="date" class="form-control" name="tanggal_target" value="{{ $project['tanggal_target'] }}">
                </div>
            </div>
        </div>
    </div>

  <button type="submit" class="btn btn-primary">Update</button>
</form>
@endsection

resources/views/Projects/index.blade.php
@extends('layouts.app')

@section('title')
    Project
@endsection 


@section('content')
<a href="{{ route('projects.create') }}" class="btn btn-secondary my-2">Tambah Project</a>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">No.</th>
      <th scope="col">Nama</th>
      <th scope="col">Tanggal Mulai</th>
      <th scope="col">Tanggal Target</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
@foreach ($projects as $project)
    <tr>
        <td>{{ $loop->iteration }}</td>
        <td>{{ $project['nama'] }}</td>
        <td>{{ $project['tanggal_mulai'] }}</td>
        <td>{{ $project['tanggal_target'] }}</td>
        <td>
                <a href="{{ route('projects.show', $project['id']) }}" class="btn btn-primary">Show</a>
                <a href="{{ route('projects.edit', $project['id']) }}" class="btn btn-primary">Edit</a>
                <form action="{{ route('projects.destroy', $project['id']) }}" method="post">
                    <input type="submit" class="btn btn-danger" value="Hapus">
                    @method('delete')
                    @csrf
                </form>
        </td>
    </tr> 
@endforeach
  </tbody>
@endsection
</table>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{ config('app.name', 'Laravel') }}</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    
</head>
<body class="py-4">
    <div class="container">
        <h1>@yield('title')</h1>
        @yield('content')
    </div>
</body>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</html>